GEOMESA-3524 Move CLI auto-complete out of maven build (#3428)
* Add git.properties to CLI tools conf dir
* Update git-commit-id-plugin from `4.9.10` to `9.0.2`

diff --git a/geomesa-tools/bin/geomesa-tools b/geomesa-tools/bin/geomesa-tools
--- a/geomesa-tools/bin/geomesa-tools
+++ b/geomesa-tools/bin/geomesa-tools
@@ -10,34 +10,41 @@
 # set environment variables in conf/geomesa-env.sh, dependencies in .dependencies
 
 # configure HOME and CONF_DIR, then load geomesa-env.sh
-localHomeDir="$(cd "`dirname "$0"`"/..; pwd)"
+localHomeDir="$(cd "$(dirname "$0")"/.. || exit; pwd)"
 export %%tools.dist.name%%_HOME="${%%tools.dist.name%%_HOME:-$localHomeDir}"
-export GEOMESA_CONF_DIR="${GEOMESA_CONF_DIR:-$%%tools.dist.name%%_HOME/conf}"
-
 if [[ ! "$%%tools.dist.name%%_HOME" -ef "$localHomeDir" ]]; then
-  echo "WARNING: %%tools.dist.name%%_HOME is pointing to $%%tools.dist.name%%_HOME, but script is being invoked from ${localHomeDir}/bin" >&2
-elif [[ ! "$GEOMESA_CONF_DIR" -ef "$%%tools.dist.name%%_HOME/conf" ]]; then
-  echo "WARNING: GEOMESA_CONF_DIR is pointing to $GEOMESA_CONF_DIR, but %%tools.dist.name%%_HOME is $%%tools.dist.name%%_HOME" >&2
+  echo >&2 "ERROR: %%tools.dist.name%%_HOME is pointing to ${%%tools.dist.name%%_HOME}, but script is being invoked from ${localHomeDir}/bin"
+  exit 1
 fi
+if [[ -n "$GEOMESA_CONF_DIR" ]] &&  [[ ! "$GEOMESA_CONF_DIR" -ef "$%%tools.dist.name%%_HOME/conf" ]]; then
+  echo >&2 "ERROR: GEOMESA_CONF_DIR is pointing to $GEOMESA_CONF_DIR, instead of ${%%tools.dist.name%%_HOME}/conf"
+  exit 1
+fi
+export GEOMESA_CONF_DIR="${%%tools.dist.name%%_HOME}/conf"
 
-RUNNER="%%tools.runner%%"
 NG_RUNNER="org.locationtech.geomesa.tools.utils.NailgunServer"
 
-if [[ -f "${GEOMESA_CONF_DIR}/geomesa-env.sh" ]]; then
-  . "${GEOMESA_CONF_DIR}/geomesa-env.sh"
-else
-  echo "ERROR: could not read '${GEOMESA_CONF_DIR}/geomesa-env.sh', aborting script" >&2
-  exit 1
+source "${GEOMESA_CONF_DIR}/geomesa-env.sh"
+source "${GEOMESA_CONF_DIR}/functions.sh"
+
+# create log dir if needed
+if [[ ! -d "${GEOMESA_LOG_DIR}" ]]; then
+  mkdir -p "${GEOMESA_LOG_DIR}"
+fi
+
+if [[ $1 = debug ]]; then
+  GEOMESA_OPTS="${GEOMESA_OPTS} ${GEOMESA_DEBUG_OPTS}"
+  shift 1
 fi
 
 function load_classpath() {
   CLASSPATH="$(get_classpath)"
   # load and check required dependencies - skip if classpath is explicitly set
   if [[ -z "$GEOMESA_CLASSPATH" && "$GEOMESA_CHECK_DEPENDENCIES" = "true" && -f "${GEOMESA_CONF_DIR}/dependencies.sh" ]]; then
-    . "${GEOMESA_CONF_DIR}/dependencies.sh"
-    includes="$(dependencies $CLASSPATH)"
+    source "${GEOMESA_CONF_DIR}/dependencies.sh"
+    includes="$(dependencies "$CLASSPATH")"
     # TODO check for --no-prompt and pass it along
-    check_classpath "$GEOMESA_LIB" "$CLASSPATH" "$includes"
+    check_classpath "$GEOMESA_LIB_DIR" "$CLASSPATH" "$includes"
     RET=$?
     if [[ $RET -eq 1 ]]; then
       # downloaded new jars - re-load the classpath to pick them up
@@ -55,11 +62,19 @@ function get_classpath() {
     echo "$GEOMESA_CLASSPATH"
   else
     local classpath
-    classpath="$(get_base_classpath)"
-    for file in $(ls "${GEOMESA_CONF_DIR}"/*-env.sh | grep -v geomesa-env.sh); do
-      local env_cp
-      env_cp="$(. "$file")"
-      classpath="$classpath:$(remove_slf4j_from_classpath "$env_cp")"
+    # include geomesa first so that the correct log4j.properties is picked up
+    classpath="${GEOMESA_CONF_DIR}:$(find_jars "$GEOMESA_LIB_DIR")"
+    # prepend user defined directories to the classpath using java classpath syntax
+    # we prepend so that they take precedence when explicitly defined by the user
+    if [[ -n "${GEOMESA_EXTRA_CLASSPATHS}" ]]; then
+      classpath="${GEOMESA_EXTRA_CLASSPATHS}:${classpath}"
+    fi
+    for file in "${GEOMESA_CONF_DIR}"/*-env.sh; do
+      if [[ -f "$file" ]] && [[ "$file" != "${GEOMESA_CONF_DIR}"/geomesa-env.sh ]]; then
+        local env_cp
+        env_cp="$(source "$file")"
+        classpath="$classpath:$(remove_slf4j_from_classpath "$env_cp")"
+      fi
     done
     classpath="$(remove_log4j1_from_classpath "$classpath")"
     classpath="$(fix_classpath_format "$classpath")"
@@ -69,34 +84,42 @@ function get_classpath() {
 
 function start_nailgun() {
   load_classpath
-  get_nailgun_options # need to use global state to pass the array for correctly handling quotes
+  local NG_OPTS=()
+  if [[ -n "$GEOMESA_NG_SERVER" ]]; then
+    NG_OPTS+=("-host" "$GEOMESA_NG_SERVER")
+  fi
+  if [[ -n "$GEOMESA_NG_PORT" ]]; then
+    NG_OPTS+=("--port" "$GEOMESA_NG_PORT")
+  fi
+  if [[ -n "$GEOMESA_NG_TIMEOUT" ]]; then
+    NG_OPTS+=("--timeout" "$GEOMESA_NG_TIMEOUT")
+  fi
+  if [[ -n "$GEOMESA_NG_IDLE" ]]; then
+    NG_OPTS+=("--idle" "$GEOMESA_NG_IDLE")
+  fi
+  if [[ -n "$GEOMESA_NG_POOL_SIZE" ]]; then
+    NG_OPTS+=("--pool-size" "$GEOMESA_NG_POOL_SIZE")
+  fi
   echo -n "Starting Nailgun server... " >&2
   # create a named pipe to read our nailgun startup output
   fd="$(mktemp --tmpdir ngfdXXXX)" && rm "$fd" && mkfifo "$fd"
-  exec 3<>$fd # tie the pipe to output 3
-  rm $fd # remove the pipe so that the process can exit normally
+  exec 3<>"$fd" # tie the pipe to output 3
+  rm "$fd" # remove the pipe so that the process can exit normally
   # start nailgun in the background and redirect output to the pipe
-  nohup java $GEOMESA_OPTS -cp $CLASSPATH $NG_RUNNER "${NG_OPTS[@]}" >&3 2>&1 </dev/null &
+  # shellcheck disable=SC2086
+  nohup java $GEOMESA_OPTS -cp "$CLASSPATH" $NG_RUNNER "${NG_OPTS[@]}" >&3 2>&1 </dev/null &
   # read the output from the nailgun start up, timeout after 60 seconds
   read -t 60 -r ng_output <&3
-  echo $ng_output >&2
-  if [[ -z $(echo $ng_output | grep started) ]]; then
+  echo "$ng_output" >&2
+  if ! echo "$ng_output" | grep -q started; then
     echo "Error starting Nailgun server" >&2
     exit 1
   fi
 }
 
-# set java process options - do this after set classpath b/c that can modify JAVA_LIBRARY_PATH
-# TODO JAVA_LIBRARY_PATH not being set, and this is being called before setting the classpath
-if [[ $1 = debug ]]; then
-  GEOMESA_OPTS="$(get_options "debug")"
-  shift 1
-else
-  GEOMESA_OPTS="$(get_options)"
-fi
 
 if [[ $1 = classpath ]]; then
-  echo "$(get_classpath)" | tr ':' '\n' | sort
+  get_classpath | tr ':' '\n' | sort
 elif [[ $1 = configure ]]; then
   geomesa_configure
 elif [[ $1 = scala-console ]]; then
@@ -108,20 +131,21 @@ elif [[ $1 = scala-console ]]; then
 elif [[ $1 = ng && $2 = start ]]; then
   start_nailgun
 elif [[ $1 = ng && $2 = stop ]]; then
-  ${%%tools.dist.name%%_HOME}/bin/ng ng-stop
+  "${%%tools.dist.name%%_HOME}"/bin/ng ng-stop
 elif [[ $1 = ng && $2 = classpath ]]; then
-  ${%%tools.dist.name%%_HOME}/bin/ng ng-cp
+  "${%%tools.dist.name%%_HOME}"/bin/ng ng-cp
 elif [[ "$GEOMESA_NG_ENABLED" = "true" ]]; then
   # check to see if the nailgun server is up
-  ${%%tools.dist.name%%_HOME}/bin/ng ng-version >/dev/null 2>&1
+  "${%%tools.dist.name%%_HOME}"/bin/ng ng-version >/dev/null 2>&1
   RET=$?
   if [[ $RET -ne 0 ]]; then
     # it's not running, start the nailgun server
     start_nailgun
   fi
   # invoke the nailgun client
-  ${%%tools.dist.name%%_HOME}/bin/ng $RUNNER "$@"
+  "${%%tools.dist.name%%_HOME}"/bin/ng "%%tools.runner%%" "$@"
 else
   load_classpath
-  java $GEOMESA_OPTS -cp $CLASSPATH $RUNNER "$@"
+  # shellcheck disable=SC2086
+  java $GEOMESA_OPTS -cp "$CLASSPATH" "%%tools.runner%%" "$@"
 fi
