GEOMESA-753 GeoMesa tools REPL
* Added 'repl' command to the tools, which drops you into the interactive scalding repl
* Repl includes scalding repl, with support for running scalding commands interactively
* Repl can be run in 'local' or 'hdfs' mode - only relevant for scalding operations
* Added local taps for accessing Accumulo and GeoMesa in local mode

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

diff --git a/geomesa-tools/bin/geomesa b/geomesa-tools/bin/geomesa
--- a/geomesa-tools/bin/geomesa
+++ b/geomesa-tools/bin/geomesa
@@ -127,42 +127,49 @@ elif [[ (-z "$ACCUMULO_CONF_DIR") || (-z "$HADOOP_CONF_DIR")]]; then
     echo >&2 ""
 fi
 
+function findJars() {
+    home="$1"
+    CP=""
+    if [ -n "$home" -a -d "$home" ]; then
+        for jar in $(find ${home} -name "*.jar"); do
+            if [[ ("$2" != "true") || (("$jar" != *"test"*) && ("$jar" != *"slf4j"*)) ]]; then
+                CP="$CP:$jar"
+            fi
+        done
+        if [ -d "$home/native" ]; then
+            if [ -z "$JAVA_LIBRARY_PATH" ]; then
+                JAVA_LIBRARY_PATH="$home/native"
+            else
+                JAVA_LIBRARY_PATH="$home/native:$JAVA_LIBRARY_PATH"
+            fi
+        fi
+    else
+        echo >&2  "Could not find directory $home. Please check to see that this directory exists, or edit
+            this script directly to specify an alternate location."
+    fi
+    if [ "${CP:0:1}" = ":" ]; then
+        CP="${CP:1}"
+    fi
+    echo $CP
+}
+
 # Start constructing GEOMESA_CP (classpath)
 # include geomesa first so that the correct log4j.properties is picked up
-GHAdirs=("$GEOMESA_LIB" "$ACCUMULO_LIB" "$HADOOP_LIB")
-for home in ${GHAdirs[*]}; do
-  if [ -n "$home" ]; then
-    for jar in $(find ${home} -name "*.jar"); do
-      GEOMESA_CP="$GEOMESA_CP:$jar"
-    done
-    if [ -d "$home/native" ]; then
-      if [ -z "$JAVA_LIBRARY_PATH" ]; then
-        JAVA_LIBRARY_PATH="$home/native"
-      else
-        JAVA_LIBRARY_PATH="$home/native:$JAVA_LIBRARY_PATH"
-      fi
-    fi
-  fi
-done
+GEOMESA_CP="$(findJars $GEOMESA_LIB):${ACCUMULO_CONF_DIR}:${HADOOP_CONF_DIR}"
+ACCUMULO_CP="$(findJars $ACCUMULO_LIB)"
 
 #Get the hadoop jars, ignoring jars with names containing slf4j and test
-hadoopDirs=("$HADOOP_COMMON" "$HADOOP_MAPREDUCE" "$HADOOP_YARN" "$HADOOP_HDFS")
+hadoopDirs=("$HADOOP_LIB" "$HADOOP_COMMON" "$HADOOP_MAPREDUCE" "$HADOOP_YARN" "$HADOOP_HDFS")
 for home in ${hadoopDirs[*]}; do
-  if [[ (-n "$home") && (-d ${home}) ]]; then
-    for jar in $(find ${home} -name "*.jar"); do
-      if [[ ("$jar" != *"test"*) && ("$jar" != *"slf4j"*) ]]; then
-        GEOMESA_CP="$GEOMESA_CP:$jar"
-      fi
-    done
-  else
-    echo >&2  "Could not find directory $home. Either check to see that this directory exists and has
-      the appropriate Hadoop JARs, or edit this script directly to specify an alternate location for the
-      Hadoop JARs."
+  tmp="$(findJars $home true)"
+  if [ -n "$tmp" ]; then
+    HADOOP_CP="$HADOOP_CP:$tmp"
+  fi
+  if [ "${HADOOP_CP:0:1}" = ":" ]; then
+    HADOOP_CP="${HADOOP_CP:1}"
   fi
 done
 
-# We explicitly add geomesa-tools as the first jar to ensure the correct log4j properties file is used.
-CLASSPATH="${GEOMESA_CP}:${ACCUMULO_CONF_DIR}:${HADOOP_CONF_DIR}"
 if [ -n "$JAVA_LIBRARY_PATH" ]; then
   GEOMESA_OPTS="$GEOMESA_OPTS,java.library.path=$JAVA_LIBRARY_PATH"
   export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JAVA_LIBRARY_PATH"
@@ -206,13 +213,26 @@ if  [[ $1 = configure ]]; then
     echo "export GEOMESA_HOME="$GEOMESA_HOME""
     echo "export PATH=\${GEOMESA_HOME}/bin:\$PATH"
 elif [[ $1 = classpath ]]; then
+    CLASSPATH="$GEOMESA_CP:$ACCUMULO_CP:$HADOOP_CP"
     for element in ${CLASSPATH//:/ } ; do
         echo ${element}
     done
+elif [[ $1 = repl ]]; then
+    if [ "$2" = "hdfs" ]; then
+        # we need to exclude slf4j, as it's already on the hadoop classpath
+        CLASSPATH="$(echo $GEOMESA_CP | sed s/[^:]*slf4j-log4j[^:]*:*//g):$ACCUMULO_CP"
+        export HADOOP_CLASSPATH="$CLASSPATH"
+        export LIBJARS="${CLASSPATH//:/,}"
+        hadoop jar $GEOMESA_HOME/lib/geomesa-tools-*.jar org.locationtech.geomesa.tools.repl.GeoMesaShell -libjars "$LIBJARS" -Dmapred.reduce.tasks=20 -Dmapred.min.split.size=2000000000 --hdfs --repl
+    else
+        CLASSPATH="$GEOMESA_CP:$ACCUMULO_CP:$HADOOP_CP"
+        java ${GEOMESA_OPTS} -cp ${CLASSPATH} org.locationtech.geomesa.tools.repl.GeoMesaShell --local --repl
+    fi
 else
     if [[ $1 = debug ]]; then
         GEOMESA_OPTS="$GEOMESA_OPTS $GEOMESA_DEBUG_OPTS"
         shift 1
     fi
+    CLASSPATH="$GEOMESA_CP:$ACCUMULO_CP:$HADOOP_CP"
     java ${GEOMESA_OPTS} -cp ${CLASSPATH} org.locationtech.geomesa.tools.Runner "$@"
 fi
