Instance type
Signed-off-by: Austin Heyne <aheyne@ccri.com>

diff --git a/geomesa-hbase/geomesa-hbase-tools/bin/aws-utils/aws-bootstrap b/geomesa-hbase/geomesa-hbase-tools/bin/aws-utils/aws-bootstrap
--- a/geomesa-hbase/geomesa-hbase-tools/bin/aws-utils/aws-bootstrap
+++ b/geomesa-hbase/geomesa-hbase-tools/bin/aws-utils/aws-bootstrap
@@ -42,6 +42,7 @@ function printHelp() {
 
 ARGS=($@)
 attributes=()
+InstanceType="InstanceType=m1.large"
 
 if [[ $# -eq 0 ]]; then
   printHelp
@@ -91,8 +92,9 @@ else
           echo "Invalid SSH key name"
           exit 1
         fi
+        shift
         ;;
-      --MasterSecurityGroups)
+      --MasterSecurityGroup*) # Group or Groups should be fine
         if [[ $2 != -* ]]; then
           shift
           MasterSecurityGroups="AdditionalMasterSecurityGroups=${1}"
@@ -101,12 +103,33 @@ else
           echo "Invalid Master Security Group"
           exit 1
         fi
+        shift
+        ;;
+      --InstanceType)
+        if [[ $2 != -* ]]; then
+          shift
+          InstanceType="InstanceType=${1}"
+        else
+          echo "Invalid Instance Type"
+          exit 1
+        fi
+        shift
+        ;;
+      --MasterInstanceType)
+        if [[ $2 != -* ]]; then
+          shift
+          MasterInstanceType="InstanceType=${1}"
+        else
+          echo "Invalid Master Instance Type"
+          exit 1
+        fi
+        shift
         ;;
       -h|--help)
         printHelp
         ;;
       *)
-        echo "Unknown argument: ${ARGS[$i]}"
+        echo "Unknown argument: ${ARGS[$1]}"
         echo "${usage}"
         exit 1
         ;;
@@ -151,6 +174,11 @@ fi
 if [[ ${#attributes[@]} -gt 1 ]]; then
   attrs=$(join_by , ${attributes[@]})
   EC2_ATTRIBUTES="--ec2-attributes ${attrs}"
+fi
+
+# If master type is not given use the same as the workers
+if [[ -z "${MasterInstanceType}" ]]; then
+  MasterInstanceType=$InstanceType
 fi
 
 echo "Starting GeoMesa AWS EMR Bootstrap Process"
@@ -231,8 +259,8 @@ cmd="
     --applications Name=Hadoop Name=Zookeeper Name=Spark Name=HBase ${ZEPPELIN_APP} \
     ${EC2_ATTRIBUTES}                                                               \
     --instance-groups                                                               \
-      Name=Master,InstanceCount=1,InstanceGroupType=MASTER,InstanceType=m1.large    \
-      Name=Workers,InstanceCount=1,InstanceGroupType=CORE,InstanceType=m1.large,BidPrice=.06     \
+      Name=Master,InstanceCount=1,InstanceGroupType=MASTER,${MasterInstanceType}    \
+      Name=Workers,InstanceCount=1,InstanceGroupType=CORE,${InstanceType},BidPrice=.06     \
     --configurations file://${hbase_conf}                                           \
     --bootstrap-actions Name=BootstrapGeoMesa,Path=${CONTAINER}.aws-bootstrap-actions.sh,Args=[${BootstrapArgs}]
 "
