GEOMESA-2880 Check and install missing dependencies in CLI tools
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

diff --git a/geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow b/geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
--- a/geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
+++ b/geomesa-arrow/geomesa-arrow-tools/bin/geomesa-arrow
@@ -7,53 +7,69 @@
 # http://www.opensource.org/licenses/apache2.0.php.
 #
 
-# Set environment variables in bin/geomesa-env.sh
+# set environment variables in conf/geomesa-env.sh, dependencies in .dependencies
 
-if [ -z "${%%gmtools.dist.name%%_HOME}" ]; then
-  export %%gmtools.dist.name%%_HOME="$(cd "`dirname "$0"`"/..; pwd)"
+# configure HOME and CONF_DIR, then load geomesa-env.sh
+export %%gmtools.dist.name%%_HOME="${%%gmtools.dist.name%%_HOME:-$(cd "`dirname "$0"`"/..; pwd)}"
+export GEOMESA_CONF_DIR="${GEOMESA_CONF_DIR:-$%%gmtools.dist.name%%_HOME/conf}"
+
+if [[ -f "${GEOMESA_CONF_DIR}/geomesa-env.sh" ]]; then
+  . "${GEOMESA_CONF_DIR}/geomesa-env.sh"
+else
+  echo >&2 "ERROR: could not read '${GEOMESA_CONF_DIR}/geomesa-env.sh', aborting script"
+  exit 1
 fi
-
-# Load common functions and setup
-. "${%%gmtools.dist.name%%_HOME}"/bin/common-functions.sh
-
-# Start constructing GEOMESA_CP (classpath)
-# include geomesa first so that the correct log4j.properties is picked up
-GEOMESA_CP="${GEOMESA_CONF_DIR}:$(findJars $GEOMESA_LIB)"
-
-# Prepend user defined directories to the classpath using java classpath syntax
-# We preprend so that they take precedence when explicitly defined by the user
-if [[ -n "${GEOMESA_EXTRA_CLASSPATHS}" ]]; then
-  GEOMESA_CP="${GEOMESA_EXTRA_CLASSPATHS}:${GEOMESA_CP}"
-fi
-
-CLASSPATH="$GEOMESA_CP"
-
-# Geomesa tools setup completed, below we parse user arguments
-#
-# configure runs the geomesa configuration, sets both the ${geomesa.dist.foobar} and PATH vars
-# classpath prints the class path, ie list of jars we are using
-# else is running actual commands in the tools
 
 if  [[ $1 = configure ]]; then
-  geomesaConfigure
-else
-  if [[ $1 = debug ]]; then
-    GEOMESA_OPTS="$GEOMESA_OPTS $GEOMESA_DEBUG_OPTS"
-    shift 1
-  fi
-  if [[ $1 = classpath ]]; then
-    for element in ${CLASSPATH//:/ }; do
-      echo ${element}
-    done
-  elif [[ $1 = scala-console ]]; then
-    # scala console requires options to be passed in through java_opts
-    export JAVA_OPTS="${GEOMESA_OPTS} ${CUSTOM_JAVA_OPTS} ${JAVA_OPTS}"
-    geomesaScalaConsole ${CLASSPATH}
+  geomesa_configure
+  exit
+fi
+
+# setup the classpath
+function get_classpath() {
+  if [[ -n "$GEOMESA_CLASSPATH" ]]; then
+    echo "$GEOMESA_CLASSPATH"
   else
-    if [[ -z "$CUSTOM_JAVA_OPTS" ]]; then
-      # if custom opts are not set, use global default
-      export CUSTOM_JAVA_OPTS="${JAVA_OPTS}"
-    fi
-    java ${GEOMESA_OPTS} ${CUSTOM_JAVA_OPTS} -cp ${CLASSPATH} org.locationtech.geomesa.arrow.tools.ArrowRunner "$@"
+    local classpath="$(get_base_classpath)"
+    classpath="$(fix_classpath_format $classpath)"
+    echo "$classpath"
   fi
+}
+
+RUNNER="org.locationtech.geomesa.arrow.tools.ArrowRunner"
+CLASSPATH="$(get_classpath)"
+
+# set java process options - do this after set classpath b/c that can modify JAVA_LIBRARY_PATH
+if [[ $1 = debug ]]; then
+  GEOMESA_OPTs="$(get_options "debug")"
+  shift 1
+else
+  GEOMESA_OPTs="$(get_options)"
+fi
+
+if [[ $1 = classpath ]]; then
+  echo $CLASSPATH | tr ':' '\n' | sort
+elif [[ $1 = scala-console ]]; then
+  shift 1
+  # scala console requires options to be passed in through java_opts
+  export JAVA_OPTS="${GEOMESA_OPTS}"
+  geomesa_scala_console ${CLASSPATH} "$@"
+else
+  # load and check required dependencies - skip if classpath is explicitly set
+  if [[ -z "$GEOMESA_CLASSPATH" && "$GEOMESA_CHECK_DEPENDENCIES" = "true" && -f "${GEOMESA_CONF_DIR}/dependencies.sh" ]]; then
+    . "${GEOMESA_CONF_DIR}/dependencies.sh"
+    includes="$(dependencies $CLASSPATH)"
+    check_classpath "$GEOMESA_LIB" "$CLASSPATH" "$includes"
+    RET=$?
+    if [[ $RET -eq 1 ]]; then
+      # downloaded new jars - re-load the classpath to pick them up
+      CLASSPATH="$(get_classpath)"
+    elif [[ $RET -ne 0 ]]; then
+       # error or cancelled
+      exit $RET
+    fi
+  fi
+
+  # invoke the main java process
+  java ${GEOMESA_OPTS} -cp ${CLASSPATH} $RUNNER "$@"
 fi
diff --git a/geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda b/geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
--- a/geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
+++ b/geomesa-lambda/geomesa-lambda-tools/bin/geomesa-lambda
@@ -7,133 +7,82 @@
 # http://www.opensource.org/licenses/apache2.0.php.
 #
 
-# Set environment variables in bin/geomesa-env.sh
+# set environment variables in conf/geomesa-env.sh, dependencies in .dependencies
 
-if [ -z "${%%gmtools.dist.name%%_HOME}" ]; then
-  export %%gmtools.dist.name%%_HOME="$(cd "`dirname "$0"`"/..; pwd)"
-fi
+# configure HOME and CONF_DIR, then load geomesa-env.sh
+export %%gmtools.dist.name%%_HOME="${%%gmtools.dist.name%%_HOME:-$(cd "`dirname "$0"`"/..; pwd)}"
+export GEOMESA_CONF_DIR="${GEOMESA_CONF_DIR:-$%%gmtools.dist.name%%_HOME/conf}"
 
-# Load common functions and setup
-. "${%%gmtools.dist.name%%_HOME}"/bin/common-functions.sh
-
-# ACCUMULO paths, user can hard set these in geomesa-env, or rely on this script to find set them via ACCUMULO_HOME
-if [[ -n "$ACCUMULO_HOME" ]]; then
-  if [[ -z "$ACCUMULO_LIB" && -d "${ACCUMULO_HOME}/lib" ]]; then
-    ACCUMULO_LIB=${ACCUMULO_HOME}/lib
-  fi
-  if [[ -z "$ACCUMULO_CONF_DIR" && -d "${ACCUMULO_HOME}/conf" ]]; then
-    ACCUMULO_CONF_DIR=${ACCUMULO_HOME}/conf
-  fi
-fi
-
-# HADOOP paths, user can hard set these in geomesa-env, or rely on this script to find set them via HADOOP_HOME
-if [[ -n "$HADOOP_HOME" ]]; then
-  if [[ -z "$HADOOP_CONF_DIR" && -d "${HADOOP_HOME}/etc/hadoop" ]]; then
-    HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
-  fi
-fi
-
-# Start constructing GEOMESA_CP (classpath)
-# include geomesa first so that the correct log4j.properties is picked up
-GEOMESA_CP="${GEOMESA_CONF_DIR}:$(findJars $GEOMESA_LIB):${ACCUMULO_CONF_DIR}:${HADOOP_CONF_DIR}"
-
-# Prepend user defined directories to the classpath using java classpath syntax
-# We preprend so that they take precedence when explicitly defined by the user
-if [[ -n "${GEOMESA_EXTRA_CLASSPATHS}" ]]; then
-  GEOMESA_CP="${GEOMESA_EXTRA_CLASSPATHS}:${GEOMESA_CP}"
-fi
-
-ACCUMULO_CP="$(findJars $ACCUMULO_LIB true true)"
-
-# Get the hadoop jars, ignoring jars with names containing slf4j and test
-# Copied from accumulo classpath
-if [[ "$hadoopCDH" == "1" ]]; then
-  # Hadoop CDH configuration
-  hadoopDirs=(
-    $HADOOP_HOME
-    $HADOOP_CONF_DIR
-    $HADOOP_COMMON_HOME
-    $HADOOP_HDFS_HOME
-    $YARN_HOME
-    $HADOOP_MAPRED_HOME
-    $HADOOP_CUSTOM_CP
-  )
+if [[ -f "${GEOMESA_CONF_DIR}/geomesa-env.sh" ]]; then
+  . "${GEOMESA_CONF_DIR}/geomesa-env.sh"
 else
-  hadoopDirs=(
-    # Hadoop 2 requirements
-    $HADOOP_HOME/share/hadoop/common
-    $HADOOP_HOME/share/hadoop/hdfs/
-    $HADOOP_HOME/share/hadoop/mapreduce/
-    $HADOOP_HOME/share/hadoop/tools/lib
-    $HADOOP_HOME/share/hadoop/yarn/
-    # HDP 2.0 requirements
-    /usr/lib/hadoop/
-    /usr/lib/hadoop-hdfs/
-    /usr/lib/hadoop-mapreduce/
-    /usr/lib/hadoop-yarn/
-    # HDP 2.2 requirements
-    /usr/hdp/current/hadoop-client/
-    /usr/hdp/current/hadoop-hdfs-client/
-    /usr/hdp/current/hadoop-mapreduce-client/
-    /usr/hdp/current/hadoop-yarn-client/
-    # IOP 4.1 requirements
-    /usr/iop/current/hadoop-client/
-    /usr/iop/current/hadoop-hdfs-client/
-    /usr/iop/current/hadoop-mapreduce-client/
-    /usr/iop/current/hadoop-yarn-client/
-  )
+  echo >&2 "ERROR: could not read '${GEOMESA_CONF_DIR}/geomesa-env.sh', aborting script"
+  exit 1
 fi
-
-for home in ${hadoopDirs[*]}; do
-  tmp="$(findJars $home true)"
-  if [[ -n "$tmp" ]]; then
-    HADOOP_CP="$HADOOP_CP:$tmp"
-  fi
-  if [[ "${HADOOP_CP:0:1}" = ":" ]]; then
-    HADOOP_CP="${HADOOP_CP:1}"
-  fi
-done
-
-# For zookeeper only include the single root jar
-if [[ -d "${ZOOKEEPER_HOME}" ]]; then
-  ZOOKEEPER_JAR="$(find -L $ZOOKEEPER_HOME -maxdepth 1 -type f -name *zookeeper*jar | head -n 1)"
-fi
-
-# load kafka jars
-if [[ -n "$KAFKA_HOME" ]]; then
-  KAFKA_CP="$(findJars $KAFKA_HOME/libs true true)"
-else
-  KAFKA_CP=""
-fi
-
-CLASSPATH="$GEOMESA_CP:$ACCUMULO_CP:$HADOOP_CP:$ZOOKEEPER_JAR:$KAFKA_CP"
-
-# Geomesa tools setup completed, below we parse user arguments
-#
-# configure | runs the geomesa configuration, sets both the ${geomesa.dist.foobar} and PATH vars
-# classpath | prints the class path, ie list of jars we are using
-# [else]    | runs actual commands in the tools
 
 if  [[ $1 = configure ]]; then
-  geomesaConfigure
-else
-  if [[ $1 = debug ]]; then
-    GEOMESA_OPTS="$GEOMESA_OPTS $GEOMESA_DEBUG_OPTS"
-    shift 1
-  fi
-  if [[ $1 = classpath ]]; then
-    for element in ${CLASSPATH//:/ }; do
-      echo ${element}
-    done
-  elif [[ $1 = scala-console ]]; then
-    # scala console requires options to be passed in through java_opts
-    export JAVA_OPTS="${GEOMESA_OPTS} ${CUSTOM_JAVA_OPTS} ${JAVA_OPTS}"
-    geomesaScalaConsole ${CLASSPATH}
+  geomesa_configure
+  exit
+fi
+
+# setup the classpath
+function get_classpath() {
+  if [[ -n "$GEOMESA_CLASSPATH" ]]; then
+    echo "$GEOMESA_CLASSPATH"
   else
-    if [[ -z "$CUSTOM_JAVA_OPTS" ]]; then
-      # if custom opts are not set, use global default
-      export CUSTOM_JAVA_OPTS="${JAVA_OPTS}"
+    local classpath="$(get_base_classpath)"
+    if [[ -f "${GEOMESA_CONF_DIR}/accumulo-env.sh" ]]; then
+      . "${GEOMESA_CONF_DIR}/accumulo-env.sh"
+      classpath="$classpath:$(get_accumulo_classpath)"
     fi
-    java ${GEOMESA_OPTS} ${CUSTOM_JAVA_OPTS} -cp ${CLASSPATH} org.locationtech.geomesa.lambda.tools.LambdaRunner "$@"
+    if [[ -f "${GEOMESA_CONF_DIR}/hadoop-env.sh" ]]; then
+      . "${GEOMESA_CONF_DIR}/hadoop-env.sh"
+      classpath="$classpath:$(get_hadoop_classpath)"
+    fi
+    if [[ -f "${GEOMESA_CONF_DIR}/kafka-env.sh" ]]; then
+      . "${GEOMESA_CONF_DIR}/kafka-env.sh"
+      classpath="$classpath:$(get_kafka_classpath)"
+    fi
+    classpath="$(fix_classpath_format $classpath)"
+    echo "$classpath"
   fi
+}
+
+RUNNER="org.locationtech.geomesa.lambda.tools.LambdaRunner"
+CLASSPATH="$(get_classpath)"
+
+# set java process options - do this after set classpath b/c that can modify JAVA_LIBRARY_PATH
+if [[ $1 = debug ]]; then
+  GEOMESA_OPTs="$(get_options "debug")"
+  shift 1
+else
+  GEOMESA_OPTs="$(get_options)"
+fi
+
+if [[ $1 = classpath ]]; then
+  echo $CLASSPATH | tr ':' '\n' | sort
+elif [[ $1 = scala-console ]]; then
+  shift 1
+  # scala console requires options to be passed in through java_opts
+  export JAVA_OPTS="${GEOMESA_OPTS}"
+  geomesa_scala_console ${CLASSPATH} "$@"
+else
+  # load and check required dependencies - skip if classpath is explicitly set
+  if [[ -z "$GEOMESA_CLASSPATH" && "$GEOMESA_CHECK_DEPENDENCIES" = "true" && -f "${GEOMESA_CONF_DIR}/dependencies.sh" ]]; then
+    . "${GEOMESA_CONF_DIR}/dependencies.sh"
+    includes="$(dependencies $CLASSPATH)"
+    # TODO check for --no-prompt in args and pass along
+    check_classpath "$GEOMESA_LIB" "$CLASSPATH" "$includes"
+    RET=$?
+    if [[ $RET -eq 1 ]]; then
+      # downloaded new jars - re-load the classpath to pick them up
+      CLASSPATH="$(get_classpath)"
+    elif [[ $RET -ne 0 ]]; then
+       # error or cancelled
+      exit $RET
+    fi
+  fi
+
+  # invoke the main java process
+  java ${GEOMESA_OPTS} -cp ${CLASSPATH} $RUNNER "$@"
 fi
