CI - Additional retries for Maven central download errors

diff --git a/.github/workflows/dash.yml b/.github/workflows/dash.yml
--- a/.github/workflows/dash.yml
+++ b/.github/workflows/dash.yml
@@ -68,11 +68,27 @@ jobs:
             changed="true"
           fi
           echo "changed=$changed" >> "$GITHUB_OUTPUT"
+      - name: Compile
+        if: steps.dependency_changes.outputs.changed == 'true'
+        id: compile
+        continue-on-error: true
+        run: |
+          set -o pipefail
+          mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS | tee -a build.log
+      - name: Compile (retry)
+        if: steps.compile.outcome=='failure'
+        run: |
+          set -o pipefail
+          # retry if the failure was due to transient download errors from maven central
+          if [[ grep -q -e 'Could not transfer artifact' -e 'Failed to read artifact descriptor' build.log ]]; then
+            RESUME_FROM="$({ grep --text 'mvn <args> -rf ' build.log || test $? = 1; } | tail -n1 | sed 's/.*-rf/-rf/')"
+            mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS $RESUME_FROM | tee -a build.log
+          else
+            exit 1
+          fi
       - name: License check
         if: steps.dependency_changes.outputs.changed == 'true'
-        run: |
-          mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS
-          mvn $MAVEN_DASH_ARGS $MAVEN_CLI_OPTS
+        run: mvn $MAVEN_DASH_ARGS $MAVEN_CLI_OPTS
       - name: Show license
         if: success() || failure()
         run: |
diff --git a/.github/workflows/spark.yml b/.github/workflows/spark.yml
--- a/.github/workflows/spark.yml
+++ b/.github/workflows/spark.yml
@@ -48,8 +48,23 @@ jobs:
           path: ~/.m2/repository/
       - name: Set Scala version
         run: ./build/scripts/change-scala-version.sh ${{ matrix.scala-version }}
-      - name: Build with Maven
-        run: mvn $MAVEN_COMPILE_SPARK_ARGS $MAVEN_CLI_OPTS -am -pl ${{ matrix.projects.list }}
+      - name: Compile
+        id: compile
+        continue-on-error: true
+        run: |
+          set -o pipefail
+          mvn $MAVEN_COMPILE_SPARK_ARGS $MAVEN_CLI_OPTS -am -pl ${{ matrix.projects.list }} | tee -a build.log
+      - name: Compile (retry)
+        if: steps.compile.outcome=='failure'
+        run: |
+          set -o pipefail
+          # retry if the failure was due to transient download errors from maven central
+          if [[ grep -q -e 'Could not transfer artifact' -e 'Failed to read artifact descriptor' build.log ]]; then
+            RESUME_FROM="$({ grep --text 'mvn <args> -rf ' build.log || test $? = 1; } | tail -n1 | sed 's/.*-rf/-rf/')"
+            mvn $MAVEN_COMPILE_SPARK_ARGS $MAVEN_CLI_OPTS -am -pl ${{ matrix.projects.list }} $RESUME_FROM | tee -a build.log
+          else
+            exit 1
+          fi
       - name: Run Spark tests
         run: mvn $MAVEN_TEST_SPARK_ARGS $MAVEN_CLI_OPTS -pl ${{ matrix.projects.list }}
       - name: Remove geomesa artifacts
